name: Deploy S3 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-letest


    steps:
    - name: Checkout code
      uses: action/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AKIA2ZIOMXSZFUS5RJXZ}}
        aws-secret-access-key: ${{secrets.96egyIzh3cw+5QJKLMOXvidL8+LKVNPQI7+bEuVe}}
        aws-region: ap-south-1

    - name: Terraform Init
      run:  terraform init

    - name: Terraform Apply
      run: terraform apply/auto-aproved

    
      

